# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eservices.proto\"\x1b\n\x0bTextRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"&\n\x11SentimentResponse\x12\x11\n\tsentiment\x18\x01 \x01(\t2R\n\x18SentimentAnalysisService\x12\x36\n\x10\x41nalyzeSentiment\x12\x0c.TextRequest\x1a\x12.SentimentResponse\"\x00\x32\x45\n\x10TextInputService\x12\x31\n\x0bProcessText\x12\x0c.TextRequest\x1a\x12.SentimentResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'services_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_TEXTREQUEST']._serialized_start=18
  _globals['_TEXTREQUEST']._serialized_end=45
  _globals['_SENTIMENTRESPONSE']._serialized_start=47
  _globals['_SENTIMENTRESPONSE']._serialized_end=85
  _globals['_SENTIMENTANALYSISSERVICE']._serialized_start=87
  _globals['_SENTIMENTANALYSISSERVICE']._serialized_end=169
  _globals['_TEXTINPUTSERVICE']._serialized_start=171
  _globals['_TEXTINPUTSERVICE']._serialized_end=240
# @@protoc_insertion_point(module_scope)
